version: '3.8'
volumes:
  uploads:
  prerender_cache:
services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/static:/var/www/static
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - uploads:/var/www/uploads
    depends_on: # Sites will be added here dynamically
      - myflashpal-frontend
      - prerender
  prerender:
    build: ./docker/prerender
    ports:
      - "3000:3000"
    environment:
      CACHE_TTL: "3600" # 1 hour cache
      CACHE_PATH: "/cache/storage.json"
    volumes:
      - prerender_cache:/cache
    depends_on:
      myflashpal-backend:
        condition: service_healthy
  myflashpal-frontend:
    build:
      context: ./sites/myflashpal
      dockerfile: ../../docker/myflashpal/react-app.Dockerfile
    depends_on:
      - myflashpal-backend
  myflashpal-backend:
    build:
      context: ./sites/myflashpal
      dockerfile: ../../docker/myflashpal/server.Dockerfile
    environment:
      - DOCKER_ENV=true
    env_file:
      - ./sites/myflashpal/server/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/api/sitemap.xml || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
