version: '3.8'
volumes:
  uploads:
services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - uploads:/var/www/uploads
    depends_on: # Sites will be added here dynamically
      - myflashpal-frontend
      - prerender
  prerender:
    build: ./docker/prerender
    ports:
      - "3000:3000"
    environment:
      CACHE_TTL: "3600" # 1 hour cache      
  myflashpal-frontend:
    build:
      context: ./sites/myflashpal
      dockerfile: ../../docker/myflashpal/react-app.Dockerfile
    depends_on:
      - myflashpal-backend
  myflashpal-backend:
    build:
      context: ./sites/myflashpal
      dockerfile: ../../docker/myflashpal/server.Dockerfile
    environment:
      - DOCKER_ENV=true
    env_file:
      - ./sites/myflashpal/server/.env
